services:
  # PostgreSQL database
  postgres-tables:
    image: postgres:16
    container_name: postgres-tables
    environment:
      POSTGRES_DB: kotlerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3822
    ports:
      - "5433:5432"
    volumes:
      - ./init/tables:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Spring Boot Application
  kotler-app:
    build: .
    container_name: kotler-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-tables:5432/kotlerdb
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres-tables:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge